#!/bin/bash

#make clean and make again with -march compiler options for the specific machine
make clean
make

#export a random number for the RNG seed. In gdb do: set env GSL_RNG_SEED 1234
export GSL_RNG_SEED=$(head -1 /dev/urandom |od -N 10 |awk '{print $2}') 
#export GSL_RNG_SEED=1234

#run the executable with the input file
./TwoDimTubes.out inputPos.dat inputMean.dat inputB.dat > out
